version: '3.6'

services:
    postgres:
        image: postgres:12
        ports:
            - 5433:5432
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db_name
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: example@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
        ports:
            - 8999:80
    redis:
        image: redis
        ports:
            - 6380:6379
